using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class DolbyAppUiFragment : BoxContainer
{

    public event Action<string>? OnNoteAdded;
    public event Action<string>? OnNoteRemoved;

    public DolbyAppUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }
}
