using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.Interface.ScreamingButton;

public sealed partial class ScreamingButton : DefaultWindow
{
    public ScreamingButton()
    {
        RobustXamlLoader.Load(this);
    }
}
